name: Docker build, push, and deploy
on:
  workflow_call:
    inputs:
      commands:
        description: "Multiline string of commands"
        required: true
        type: string

jobs:
  read-inputs:
    name: "Convert input commands to list"
    runs-on: ubuntu-latest
    steps:
      - name: Convert commands to json array
        run: |
          cat << EOF > commands.txt
          ${{ inputs.commands }}
          EOF
          commands="$(cat commands.txt | jq --raw-input '[.]' | jq --slurp -c 'add | {cmd: .}')
          echo "${commands}"
          echo "::set-output name=matrix::${commands}"
  test-matrix:
    needs: [read-inputs]
    name: "Print inputs"
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ fromJson(needs.read-inputs.outputs) }}
