name: Docker build, push, and deploy
on:
  workflow_call:
    inputs:
      commands:
        description: "Multiline string of commands"
        required: true
        type: string

jobs:
  read-inputs:
    name: "Convert input commands to list"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
      - id: build-matrix
        name: Convert commands to json array
        run: |
          # Convert multiline string to a json array while filtering blank lines
          commands=$(echo "${{ inputs.commands }}" | jq --raw-input '[. | select(0 < length)]' | jq --slurp -c 'add | {cmd: .}')
          echo "${commands}"
          echo "::set-output name=matrix::${commands}"
  test-matrix:
    needs: [read-inputs]
    name: "Print inputs"
    strategy:
      matrix: ${{ fromJson(needs.read-inputs.outputs.matrix) }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ matrix.cmd }}
