name: Docker build, push, and deploy
on:
  workflow_call:
    inputs:
      name:
        description: "Application / container name"
        required: true
        type: string
      yaml-path:
        description: "Path to YAML manifests. Must include trailing slash if set"
        type: string
        default: ""
      file:
        description: "Path to Dockerfile"
        required: false
        type: string
        default: "Dockerfile"
      context:
        description: "Path to docker build context"
        required: false
        type: string
        default: "."

jobs:
  deploy:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: asdf-vm/actions/install@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          role-to-assume: arn:aws:iam::911907402684:role/github
          aws-region: us-west-2

      - name: Access EKS
        run: |
          cluster_name="$(dig +short txt aaronbatilo.dev | jq -r '. | fromjson.cluster_name')"
          aws eks update-kubeconfig --name "${cluster_name}"

      - name: Create buildx daemon
        uses: docker/setup-buildx-action@v1

      - name: Set docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/abatilo/${{ inputs.name }}
          tags: |
            type=sha,prefix=

      - uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=registry,ref=ghcr.io/abatilo/${{ inputs.name }}:buildcache
          cache-to: type=registry,ref=ghcr.io/abatilo/${{ inputs.name }}:buildcache,mode=max
          push: true
          file: ${{ inputs.file }}
          context: ${{ inputs.context }}

      - name: Deploy
        run: |
          sed -i 's/DOCKER_TAG/${{ steps.meta.outputs.version }}/' ${{ inputs.yaml-path }}${{ inputs.name }}.yaml
          kubectl apply -f ${{ inputs.name }}.yaml
