name: Docker build and push
on:
  workflow_call:
    inputs:
      name:
        description: "Application / container name"
        required: true
        type: string
      file:
        description: "Path to Dockerfile"
        required: false
        type: string
        default: "Dockerfile"
      context:
        description: "Path to docker build context"
        required: false
        type: string
        default: "."

jobs:
  push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Create buildx daemon
        uses: docker/setup-buildx-action@v3

      - name: Set docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/abatilo/${{ inputs.name }}
          tags: |
            type=sha,prefix=

      - uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          file: ${{ inputs.file }}
          context: ${{ inputs.context }}
