name: Docker build, push, and deploy
on:
  workflow_call:
    inputs:
      name:
        description: "Application / container name"
        required: true
        type: string

jobs:
  deploy:
    name: Build, push, and deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: asdf-vm/actions/install@v1

      - name: Access EKS
        env:
          AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/awscreds
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE
          aws eks update-kubeconfig --name usw2-r

      - name: Create buildx daemon
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/abatilo/${{ inputs.name }}:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/abatilo/${{ inputs.name }}:buildcache
          cache-to: type=registry,ref=ghcr.io/abatilo/${{ inputs.name }}:buildcache,mode=max
          labels: |
            org.opencontainers.image.source=https://github.com/abatilo/${{ inputs.name }}

      - name: Deploy
        run: |
          sed -i 's/DOCKER_TAG/${{ github.sha }}/' ${{ inputs.name }}.yaml
          kubectl apply -f ${{ inputs.name }}.yaml
